[package]
name = "example"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
wire = { path = "../wire" }

[build-dependencies]
wire-build = { path = "../wire-build" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
