[package]
name = "wire-build"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
glob = "0.3"
quote = "1.0.42"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }
